### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by MichWouters** [lun0r/Drimon-PPP#25]
https://github.com/lun0r/Drimon-PPP/blob/c9a367d1ba82be13d3e4c6e886332b65d2ecfd08/Drimon-Temp/Bestelling.cs#L110

De code in de switch statements doen grotendeels hetzelfde. Kan je de duplicate code in een nieuwe methode extracten?

**Comment by Dries-Maes** [comment]
akkoord, merci :-)
