### ISSUE TITLE
default statement toevoegen aan switch

### ISSUE THREAD

**Issue by MichWouters** [lun0r/Drimon-PPP#26]
https://github.com/lun0r/Drimon-PPP/blob/c9a367d1ba82be13d3e4c6e886332b65d2ecfd08/Drimon-Temp/Bestelling.cs#L157

Wat gebeurt er als een gebruiker een waarde groter dan 3 of een letter intypt? Met een default statement van je alle niet ondersteunde mogelijkheden op, met bv. een foutboodschap.

**Comment by Dries-Maes** [comment]
Dit wordt opgevangen in de kiezer methode, die zal dus enkel de toegelaten waarden weergeven. Niet relvant dus hier, maar zo'n default statement was een waardig alternatief geweest :-)
