### ISSUE TITLE
Witruimte boven en onder switch, if, for etc. statements

### ISSUE THREAD

**Issue by MichWouters** [lun0r/Drimon-PPP#27]
https://github.com/lun0r/Drimon-PPP/blob/c9a367d1ba82be13d3e4c6e886332b65d2ecfd08/Drimon-Temp/BestellingMenu.cs#L14

Voeg voldoende witruimte toe aan je code. Voor en na code die curly braces {} gebruikt , zoals if, for, switch... wordt meestal een regel witruimte geplaatst.

var code = 123;

if(true)
{
   // do stuff
}

foreach(var vars in list)
{
   // do stuff
}

// More code

**Comment by Dries-Maes** [comment]
zal er op letten!
